server:
  port: 8080
spring:
  application:
    name: mbroker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://mb-dev-dc1:20202/mb_backend
    #url: jdbc:postgresql://localhost:40002/mb_backend

    username: mb_backend
    password: mb_backend
  liquibase:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev.smartdeal.pro/api/v1/token/public-key
          jws-algorithm: RS384
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  logging:
    level:
      org.hibernate: DEBUG

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 180000
        loggerLevel: FULL

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
api:
  cian:
    token-url: ${CIAN_TOKEN_URL:https://api.cian.ru}
    token-path: ${CIAN_TOKEN_PATH:/identity/connect/token} #todo когда будем запрашивать токен вбить его сюда
    api-url: ${CIAN_API_URL:https://api.cian.ru}
    real-estate-path : ${CIAN_REAL_ESTATE_URL:/newbuilding-mortgage-calculator/v1/get-newbuildings/}
program_path: "/app/src/main/resources/programs/programs_202312281115.csv"
bank_future_rules_path: "/app/src/main/resources/programs/bank_feature_rules_202312281115.csv"
additional_rate_rules_path: "/app/src/main/resources/programs/additional_rate_rules_202312281115.csv"