server:
  port: 8080
spring:
  application:
    name: mbroker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://sd-dev:20101/mortgage_broker
    username: mortgage_broker
    password: mortgage_broker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev.smartdeal.pro/api/v1/token/public-key
          jws-algorithm: RS384
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  logging:
    level:
      org.hibernate: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

#https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 180000
        loggerLevel: FULL

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

font_path: "/forms/ru_Arial.ttf"
form_path_docx: "forms/form.docx"
footer_path: "/forms/image/smartDeal.jpg"
fit_width_image: 100
fit_height_image: 100
left_position_image: 35
bottom_position_image: 18
page_number_front_size: 8
page_number_right_offset: 38
page_number_bottom_offset: 21