server:
  port: 8080
spring:
  application:
    name: mbroker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://mb-dev-dc1:20102/mb_backend
    username: mb_backend
    password: mb_backend
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev.smartdeal.pro/api/v1/token/public-key
          jws-algorithm: RS384
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

#https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 180000
        loggerLevel: FULL

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

font_path: "/forms/calibri.ttf"
form_path_html: "forms/form.html"
footer_path: "/forms/image/smartDeal.jpg"
fit_width_image: 100
fit_height_image: 100
left_position_image: 35
bottom_position_image: 18
page_number_front_size: 8
page_number_right_offset: 38
page_number_bottom_offset: 21

api:
  cian:
    token-url: ${CIAN_TOKEN_URL:https://api.cian.ru}
    token-path: ${CIAN_TOKEN_PATH:/identity/connect/token} #todo когда будем запрашивать токен вбить его сюда
    api-url: ${CIAN_API_URL:https://api.cian.ru}
    real-estate-path: ${CIAN_REAL_ESTATE_URL:/newbuilding-mortgage-calculator/v1/get-newbuildings/}
cian:
  credit-program:
    make-inactive: true
    loading_credit_program:
      scheduled:
        enabled: true
        interval: 604800000 #в млсек, каждый час
    program_path: "/programs/2024-02-13/programs_4_5_7_240213.csv"
    bank_future_rules_path: "/programs/2024-02-01/bank_feature_rules.csv"
    additional_rate_rules_path: "/programs/2024-02-01/additional_rate_rules.csv"
  gk:
    scheduled:
      enabled: true
      interval: 3600000 #в млсек, каждый час
      interval-in-cron:

aws:
  accessKey: "f156ae0186764773bc9dbe898111911b"
  secretKey: "1d5910ff12ee4fafbb02aef353317b1e"
  s3:
    region: "ru-1"
    service-endpoint: "s3.ru-1.storage.selcloud.ru"
    bucket-name: "mb-dev-dc1-01"
    path:
      bank-logo: "logo/bank/"
